<?php

// ---------------------------------------------------------------------------------------
// consultas do sistema
// ---------------------------------------------------------------------------------------


$arrConsultas = array(
					"objetosEmProcessamento" => array("titulo" => "Objetos - Em processamento",
													"titulo_det" => "",
													"link" => "frm_objeto",
													"campo" => "",
													"layerCampo" => "",
													"tabelas" => "OBJETO",
													"tabelaPrincipal" => "OBJETO",
													"campoChave" => "SEQ",
													"colunas" => "SEQ as SEQ, if(notificar = 1, 'ON', 'OFF') as NOTIF, ordem as Ordem, cod_rastreamento as Código, nome as NOME, date_format(dt_envio, ASP%d/%m/%Y %H:%i:%sASP) as Data_de_Envio, date_format(dt_ult_atualizacao, ASP%d/%m/%Y %H:%i:%sASP) as Ult_Atualizacao",
													"nroValores" => "",
													"valoresAtuais" => "",
													"camposPesquisa" => "Rastreio^COD_RASTREAMENTO",
													"submete" => "",
													"count" => MAX_ROWS_VIEW,
													"chaveInicial" => "",
													"chavePrincipal" => "COD_RASTREAMENTO",
													"campoFiltro" => "",
													"join" => "",
													"orderBy" => "DT_ULT_ATUALIZACAO DESC",
													"filtroAdicional" => "status = 1"),
					"objetosEmRascunho" => array("titulo" => "Objetos - Em Rascunho",
													"titulo_det" => "",
													"link" => "frm_objeto",
													"campo" => "",
													"layerCampo" => "",
													"tabelas" => "OBJETO",
													"tabelaPrincipal" => "OBJETO",
													"campoChave" => "SEQ",
													"colunas" => "SEQ as SEQ, if(notificar = 1, 'ON', 'OFF') as NOTIF, ordem as Ordem, cod_rastreamento as Código, nome as NOME, date_format(dt_envio, ASP%d/%m/%Y %H:%i:%sASP) as Data_de_Envio",
													"nroValores" => "",
													"valoresAtuais" => "",
													"camposPesquisa" => "Rastreio^COD_RASTREAMENTO",
													"submete" => "",
													"count" => MAX_ROWS_VIEW,
													"chaveInicial" => "",
													"chavePrincipal" => "COD_RASTREAMENTO",
													"campoFiltro" => "",
													"join" => "",
													"orderBy" => "ORDEM",
													"filtroAdicional" => "status = 0"),
					"objetosEntregues" => array("titulo" => "Objetos - Entregues",
													"titulo_det" => "",
													"link" => "frm_objeto",
													"campo" => "",
													"layerCampo" => "",
													"tabelas" => "OBJETO",
													"tabelaPrincipal" => "OBJETO",
													"campoChave" => "SEQ",
													"colunas" => "SEQ as SEQ, ordem as Ordem, cod_rastreamento as Código, nome as NOME, date_format(dt_envio, ASP%d/%m/%Y %H:%i:%sASP) as Data_de_Envio",
													"nroValores" => "",
													"valoresAtuais" => "",
													"camposPesquisa" => "Rastreio^COD_RASTREAMENTO",
													"submete" => "",
													"count" => MAX_ROWS_VIEW,
													"chaveInicial" => "",
													"chavePrincipal" => "COD_RASTREAMENTO",
													"campoFiltro" => "",
													"join" => "",
													"orderBy" => "dt_envio DESC",
													"filtroAdicional" => "status = 2"),
					"objetosArquivados" => array("titulo" => "Objetos - Arquivados",
													"titulo_det" => "",
													"link" => "frm_objeto",
													"campo" => "",
													"layerCampo" => "",
													"tabelas" => "OBJETO",
													"tabelaPrincipal" => "OBJETO",
													"campoChave" => "SEQ",
													"colunas" => "SEQ as SEQ, ordem as Ordem, cod_rastreamento as Código, nome as NOME, date_format(dt_envio, ASP%d/%m/%Y %H:%i:%sASP) as Data_de_Envio",
													"nroValores" => "",
													"valoresAtuais" => "",
													"camposPesquisa" => "Rastreio^COD_RASTREAMENTO",
													"submete" => "",
													"count" => MAX_ROWS_VIEW,
													"chaveInicial" => "",
													"chavePrincipal" => "COD_RASTREAMENTO",
													"campoFiltro" => "",
													"join" => "",
													"orderBy" => "dt_envio DESC",
													"filtroAdicional" => "status = 3"),
					"objetosExtraviados" => array("titulo" => "Objetos - Extraviados",
													"titulo_det" => "",
													"link" => "frm_objeto",
													"campo" => "",
													"layerCampo" => "",
													"tabelas" => "OBJETO",
													"tabelaPrincipal" => "OBJETO",
													"campoChave" => "SEQ",
													"colunas" => "SEQ as SEQ, ordem as Ordem, cod_rastreamento as Código, nome as NOME, date_format(dt_envio, ASP%d/%m/%Y %H:%i:%sASP) as Data_de_Envio",
													"nroValores" => "",
													"valoresAtuais" => "",
													"camposPesquisa" => "Rastreio^COD_RASTREAMENTO",
													"submete" => "",
													"count" => MAX_ROWS_VIEW,
													"chaveInicial" => "",
													"chavePrincipal" => "COD_RASTREAMENTO",
													"campoFiltro" => "",
													"join" => "",
													"orderBy" => "dt_envio DESC",
													"filtroAdicional" => "status = 4"),
					"objetos" => array("titulo" => "Objetos - Todos",
													"titulo_det" => "",
													"link" => "frm_objeto",
													"campo" => "",
													"layerCampo" => "",
													"tabelas" => "OBJETO, STATUS_OBJETO",
													"tabelaPrincipal" => "OBJETO",
													"campoChave" => "SEQ",
													"colunas" => "SEQ as SEQ, cod_rastreamento as Código, nome as NOME, date_format(dt_inclusao, ASP%d/%m/%Y %H:%i:%sASP) as Data_de_Inclusão, status_objeto.descricao as STATUS",
													"nroValores" => "",
													"valoresAtuais" => "",
													"camposPesquisa" => "Rastreio^COD_RASTREAMENTO",
													"submete" => "",
													"count" => MAX_ROWS_VIEW,
													"chaveInicial" => "",
													"chavePrincipal" => "COD_RASTREAMENTO",
													"campoFiltro" => "",
													"filtroAdicional" => "",
													"join" => "status_objeto.cod_status = objeto.status",
													"orderBy" => "STATUS",
													"filtroAdicional" => ""),
					"status" => array("titulo" => "Status - Todos",
													"titulo_det" => "",
													"link" => "frm_status",
													"campo" => "",
													"layerCampo" => "",
													"tabelas" => "STATUS_OBJETO",
													"tabelaPrincipal" => "STATUS_OBJETO",
													"campoChave" => "cod_status",
													"colunas" => "cod_status as COD, cod_status as CODIGO, descricao as DESCRICAO",
													"nroValores" => "",
													"valoresAtuais" => "",
													"camposPesquisa" => "descricao^DESCRICAO",
													"submete" => "",
													"count" => MAX_ROWS_VIEW,
													"chaveInicial" => "",
													"chavePrincipal" => "COD_STATUS",
													"campoFiltro" => "",
													"filtroAdicional" => "",
													"join" => "",
													"orderBy" => "COD_STATUS",
													"filtroAdicional" => ""),
					"localidades" => array("titulo" => "Localidades dos Servidores",
													"titulo_det" => "",
													"link" => "frm_localidade",
													"campo" => "",
													"layerCampo" => "",
													"tabelas" => "LOCALIDADE",
													"tabelaPrincipal" => "LOCALIDADE",
													"campoChave" => "seq",
													"colunas" => "seq as COD, descricao as DESCRICAO, ip_servidores as SERVIDORES",
													"nroValores" => "",
													"valoresAtuais" => "",
													"camposPesquisa" => "descricao^DESCRICAO",
													"submete" => "",
													"count" => MAX_ROWS_VIEW,
													"chaveInicial" => "",
													"chavePrincipal" => "SEQ",
													"campoFiltro" => "",
													"filtroAdicional" => "",
													"join" => "",
													"orderBy" => "SEQ",
													"filtroAdicional" => ""),
					"sqlqueries" => array("titulo" => "SQL Queries - Todos",
													"titulo_det" => "",
													"link" => "frm_sql_query",
													"campo" => "",
													"layerCampo" => "",
													"tabelas" => "SQL_QUERY",
													"tabelaPrincipal" => "SQL_QUERY",
													"campoChave" => "SEQ",
													"colunas" => "SEQ as SEQ, db as DB, descricao as Descrição, tag1 as Tag1, tag2 as Tag2, tag3 as Tag3, date_format(dt_inclusao, ASP%d/%m/%YASP) as Data_de_Inclusão",
													"nroValores" => "",
													"valoresAtuais" => "",
													"camposPesquisa" => "Descricao^DESCRICAO",
													"submete" => "",
													"count" => MAX_ROWS_VIEW,
													"chaveInicial" => "",
													"chavePrincipal" => "SEQ",
													"campoFiltro" => "",
													"filtroAdicional" => "",
													"join" => "",
													"orderBy" => "",
													"filtroAdicional" => ""),
					"servidoresPorNome" => array("titulo" => "Servidores - Por Nome",
													"titulo_det" => "",
													"link" => "frm_servidor",
													"campo" => "",
													"layerCampo" => "",
													"tabelas" => "SERVIDOR, LOCALIDADE",
													"tabelaPrincipal" => "SERVIDOR",
													"campoChave" => "seq",
													"colunas" => "SERVIDOR.seq as SEQ, nome_servidor as NOME_SERVIDOR, if(ativo = 1, 'ON', 'OFF') as ATIVO, if(down_notificar = 1, 'ON', 'OFF') as DOWN_NOTIF, if(log = 1, 'ON', 'OFF') as LOG, LOCALIDADE.descricao as LOCAL, host as HOST, ip as IP, username as USUARIO, if(temperatura = 1, 'ON', 'OFF') as TEMP, if(temperatura_notificar = 1, 'ON', 'OFF') as T_NOTIF, temperatura_limite as T_LIM, if(cpu = 1, 'ON', 'OFF') as CPU, if(cpu_notificar = 1, 'ON', 'OFF') as C_NOTIF, cpu_limite as C_LIM, if(memoria = 1, 'ON', 'OFF') as MEMORIA, if(memoria_notificar = 1, 'ON', 'OFF') as M_NOTIF, memoria_limite as M_LIM, if(espaco_disco = 1, 'ON', 'OFF') as DISCO, if(espaco_disco_notificar = 1, 'ON', 'OFF') as D_NOTIF, espaco_disco_limite as D_LIM",
													"nroValores" => "",
													"valoresAtuais" => "",
													"camposPesquisa" => "nome_servidor^NOME_SERVIDOR",
													"submete" => "",
													"count" => MAX_ROWS_VIEW,
													"chaveInicial" => "",
													"chavePrincipal" => "SEQ",
													"campoFiltro" => "",
													"filtroAdicional" => "",
													"join" => "LOCALIDADE.seq = SERVIDOR.cod_localidade",
													"orderBy" => "NOME_SERVIDOR",
													"filtroAdicional" => ""),
					"usuariosPorUsername" => array("titulo" => "Usuários - Por Username",
													"titulo_det" => "",
													"link" => "frm_usuario",
													"campo" => "",
													"layerCampo" => "",
													"tabelas" => "USUARIO",
													"tabelaPrincipal" => "USUARIO",
													"campoChave" => "seq",
													"colunas" => "SEQ as SEQ, usuario as USUARIO, nome as Nome, email as EMail, nivel as NIVEL, date_format(dt_inclusao, ASP%d/%m/%YASP) as Data_de_Inclusão",
													"nroValores" => "",
													"valoresAtuais" => "",
													"camposPesquisa" => "Usuario^USUARIO",
													"submete" => "",
													"count" => MAX_ROWS_VIEW,
													"chaveInicial" => "",
													"chavePrincipal" => "SEQ",
													"campoFiltro" => "",
													"filtroAdicional" => "",
													"join" => "",
													"orderBy" => "USUARIO",
													"filtroAdicional" => ""),
					"usuariosPorNome" => array("titulo" => "Usuários - Por Nome",
													"titulo_det" => "",
													"link" => "frm_usuario",
													"campo" => "",
													"layerCampo" => "",
													"tabelas" => "USUARIO",
													"tabelaPrincipal" => "USUARIO",
													"campoChave" => "seq",
													"colunas" => "SEQ as SEQ, nome as Nome, usuario as USUARIO, email as EMail, nivel as NIVEL, date_format(dt_inclusao, ASP%d/%m/%YASP) as Data_de_Inclusão",
													"nroValores" => "",
													"valoresAtuais" => "",
													"camposPesquisa" => "Nome^NOME",
													"submete" => "",
													"count" => MAX_ROWS_VIEW,
													"chaveInicial" => "",
													"chavePrincipal" => "SEQ",
													"campoFiltro" => "",
													"filtroAdicional" => "",
													"join" => "",
													"orderBy" => "NOME",
													"filtroAdicional" => ""),
					"logsPorData" => array("titulo" => "Logs - Por Data",
													"titulo_det" => "",
													"link" => "frm_log",
													"campo" => "",
													"layerCampo" => "",
													"tabelas" => "LOG_SISTEMA",
													"tabelaPrincipal" => "LOG_SISTEMA",
													"campoChave" => "NRO_LOG_SISTEMA",
													"colunas" => "NRO_LOG_SISTEMA as NRO_LOG_SISTEMA, date_format(dt_lancamento, ASP%d/%m/%Y %H:%i:%sASP) as DT_LANCAMENTO, usuario as USUARIO, objeto as OBJETO, referencia as REFERENCIA, tipo as TIPO, hostname as HOSTNAME, ip as IP, observacao as OBS",
													"nroValores" => "",
													"valoresAtuais" => "",
													"camposPesquisa" => "Data^DT_LANCAMENTO",
													"submete" => "",
													"count" => MAX_ROWS_VIEW,
													"chaveInicial" => "",
													"chavePrincipal" => "NRO_LOG_SISTEMA",
													"campoFiltro" => "",
													"filtroAdicional" => "",
													"join" => "",
													"orderBy" => "date_format(dt_lancamento, '%Y/%m/%d %H:%i:%s') DESC",
													"filtroAdicional" => ""),
					"logsPorUsuario" => array("titulo" => "Logs - Por Usuário",
													"titulo_det" => "",
													"link" => "frm_log",
													"campo" => "",
													"layerCampo" => "",
													"tabelas" => "LOG_SISTEMA",
													"tabelaPrincipal" => "LOG_SISTEMA",
													"campoChave" => "NRO_LOG_SISTEMA",
													"colunas" => "NRO_LOG_SISTEMA as NRO_LOG_SISTEMA, usuario as USUARIO, date_format(dt_lancamento, ASP%d/%m/%Y %H:%i:%sASP) as DT_LANCAMENTO, objeto as OBJETO, referencia as REFERENCIA, tipo as TIPO, hostname as HOSTNAME, ip as IP, observacao as OBS",
													"nroValores" => "",
													"valoresAtuais" => "",
													"camposPesquisa" => "Usuario^USUARIO",
													"submete" => "",
													"count" => MAX_ROWS_VIEW,
													"chaveInicial" => "",
													"chavePrincipal" => "NRO_LOG_SISTEMA",
													"campoFiltro" => "",
													"filtroAdicional" => "",
													"join" => "",
													"orderBy" => "USUARIO, date_format(dt_lancamento, '%Y/%m/%d %H:%i:%s') DESC ",
													"filtroAdicional" => ""),													
					"logServidorPorData" => array("titulo" => "Logs Servidor - Por Data",
													"titulo_det" => "",
													"link" => "frm_log_servidor",
													"campo" => "",
													"layerCampo" => "",
													"tabelas" => "LOG_SERVIDOR,SERVIDOR",
													"tabelaPrincipal" => "LOG_SERVIDOR",
													"campoChave" => "LOG_SERVIDOR.SEQ",
													"colunas" => "LOG_SERVIDOR.SEQ as SEQ, nome_servidor as SERVIDOR, date_format(dt_registro, ASP%d/%m/%Y %H:%i:%sASP) as DATA, temp as TEMP, cpu_load as CPU, mem_used as MEM_USED, mem_free as MEM_FREE, disk1_used as D1_USED, disk1_free as D1_FREE, disk2_used as D2_USED, disk2_free as D2_FREE, disk3_used as D3_USED, disk3_free as D3_FREE",
													"nroValores" => "",
													"valoresAtuais" => "",
													"camposPesquisa" => "DATA^DT_REGISTRO",
													"submete" => "",
													"count" => MAX_ROWS_VIEW,
													"chaveInicial" => "",
													"chavePrincipal" => "LOG_SERVIDOR.SEQ",
													"campoFiltro" => "",
													"filtroAdicional" => "",
													"join" => "servidor.seq = log_servidor.seq_servidor",
													"orderBy" => "date_format(dt_registro, '%Y/%m/%d %H:%i:%s'), SEQ_SERVIDOR ",
													"filtroAdicional" => ""),													
					"esquemaCores" => array("titulo" => "Esquemas de Cores",
													"titulo_det" => "",
													"link" => "frm_esquema_cores",
													"campo" => "",
													"layerCampo" => "",
													"tabelas" => "ESQUEMA_CORES",
													"tabelaPrincipal" => "ESQUEMA_CORES",
													"campoChave" => "SEQ",
													"colunas" => "SEQ AS SEQ, descricao as DESCRICAO, bg1 as BG1, bg2 as BG2, table1 as TABLE1, table2 as TABLE2, table3 as TABLE3, botao_form as B_FORM, rastreamento_cabec as R_CABEC, rastreamento_botao as R_BOT",
													"nroValores" => "",
													"valoresAtuais" => "",
													"camposPesquisa" => "Descricao^DESCRICAO",
													"submete" => "",
													"count" => MAX_ROWS_VIEW,
													"chaveInicial" => "",
													"chavePrincipal" => "SEQ",
													"campoFiltro" => "",
													"filtroAdicional" => "",
													"join" => "",
													"orderBy" => "DESCRICAO",
													"filtroAdicional" => ""),													
					"parametros" => array("titulo" => "Parâmetros do Sistema",
													"titulo_det" => "",
													"link" => "frm_parametro",
													"campo" => "",
													"layerCampo" => "",
													"tabelas" => "PARAMETRO",
													"tabelaPrincipal" => "PARAMETRO",
													"campoChave" => "SEQ",
													"colunas" => "SEQ AS SEQ, nome as NOME, valor as VALOR, descricao as DESCRICAO",
													"nroValores" => "",
													"valoresAtuais" => "",
													"camposPesquisa" => "Nome^NOME",
													"submete" => "",
													"count" => MAX_ROWS_VIEW,
													"chaveInicial" => "",
													"chavePrincipal" => "SEQ",
													"campoFiltro" => "",
													"filtroAdicional" => "",
													"join" => "",
													"orderBy" => "NOME",
													"filtroAdicional" => ""),													
					);


					
?>